---
- name: Create a10_slb_service_group instance
  a10_slb_service_group:
      a10_host: "{{ inventory_hostname }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      name: ANSIBLE-SG1
      protocol: tcp
      lb_method: round-robin
      stats_data_action: stats-data-enable
      member_list:
      - name: "server1"
        port: 80
      - name: "server2"
        port: 80


- name: Create a10_slb_service_group instance
  a10_slb_service_group:
      a10_host: "{{ inventory_hostname }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      name: ANSIBLE-SG2
      protocol: tcp
      lb_method: round-robin
      stats_data_action: stats-data-enable
      member_list:
      - name: "server1"
        port: 8080
      - name: "server2"
        port: 8080
